---
title: "MIS 500 Porfolio"
author: "Michael Pearson"
date: "2/3/2020"
output:
  word_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```

This is some stuff to get writing going

``` {r data analysis}
## Connect to the page and download the zipped files

temp <- tempfile()

download.file("https://archive.ics.uci.edu/ml/machine-learning-databases/00296/dataset_diabetes.zip", temp)

post_zipped <- unzip(temp)

print(post_zipped)



diabetes_data <- read.csv("./dataset_diabetes/diabetic_data.csv", header = TRUE)

print(head(diabetes_data))

## Convert to a data table for easier subsetting

## Now convert to a data table so that the genders can be broken out into separate tables for analysis

library(data.table)
library(reshape2)
library(dplyr)
library(ggplot2)
##diabetes_data <- data.table(diabetes_data)
##setkey(diabetes_data, gender)
##males <- diabetes_data["Male"]
##females <- diabetes_data["Female"]
##setkey(diabetes_data, readmitted)
##more_than_30 <- diabetes_data[">30"]
##less_than_30 <- diabetes_data["<30"]

##nope <- diabetes_data["NO"]
##setkey(nope, gender)
##male_nope <- nope["Male"]
##female_nope <- nope["Female"]
##setkey(more_than_30, gender)
##male_more_than_30 <- more_than_30["Male"]
##female_more_than_30 <- more_than_30["Female"]
##setkey(less_than_30, gender)
##male_less_than_30 <- less_than_30["Male"]
##female_less_than_30 <- less_than_30["Female"]

## For plotting
gender_readmit <- diabetes_data[, c(4,50)]

try <- table(gender_readmit)
gender_readmit_table <- try[1:2,]
colnames(gender_readmit_table) <- c("re-ad < 30 days", "re-ad > 30 days", "no re-ad")
colors <- c("red", "blue")
barplot(gender_readmit_table, main = "Readmissions by Gender", ylab = "Total", beside = TRUE, col = colors)
legend("topleft", c("female", "male"), fill = colors)
try1 <- data.table(gender_readmit_table)

ggplot(try1 %>% group_by(readmitted) , aes(x = readmitted, y = N, fill = gender, cumulative = TRUE)) + geom_col()

ggplot(try1 %>% group_by(readmitted) %>% mutate(perc = round(N/sum(N),2)), aes(x = readmitted, y = perc, fill = gender, cumulative = TRUE)) + geom_col() +
 geom_text(aes(label = paste0(perc*100,"%")), 
              position = position_stack(vjust = 0.5))

race_readmit <- diabetes_data[, c(3,50)]

race_readmit_table <- table(race_readmit)
race_readmit_table <- race_readmit_table[2:5,]
colnames(race_readmit_table) <- c("re-ad < 30 days", "re-ad > 30 days", "no re-ad")
rcolors <- c("red", "blue", "green", "yellow")
barplot(race_readmit_table, main = "Readmission by Race", ylab = "Total", beside = TRUE, col = rcolors)
legend("topleft", legend = c("african/american", "Asian", "Caucasian", "Hispanic"), fill = rcolors)

race_readmit_table_1 <- data.table(race_readmit_table)

ggplot(race_readmit_table_1 %>% group_by(readmitted) , aes(x = readmitted, y = N, fill = race, cumulative = TRUE)) + geom_col()

ggplot(race_readmit_table_1 %>% group_by(readmitted) %>% mutate(perc = round(N/sum(N),2)), aes(x = readmitted, y = perc, fill = race, cumulative = TRUE)) + geom_col() +
 geom_text(aes(label = paste0(perc*100,"%")), 
              position = position_stack(vjust = 0.5))


age_readmit <- diabetes_data[, c(5,50)]
age_readmit_table <- table(age_readmit)
colnames(age_readmit_table) <- c("re-ad < 30 days", "re-ad > 30 days", "no re-ad")
par(mfrow=c(1, 1), mar=c(5, 5, 4, 8))
barplot(age_readmit_table, main = "Readmission by Age", ylab="age", legend.text = TRUE, beside = TRUE, col = rainbow(3),args.legend = list(x = "topright", bty = "n", inset=c(-0.5, 0)))

age_readmit_table_1 <- data.table(age_readmit_table)
ggplot(age_readmit_table_1 %>% group_by(readmitted) , aes(x = readmitted, y = N, fill = age, cumulative = TRUE)) + geom_col()

ggplot(age_readmit_table_1 %>% group_by(readmitted) %>% mutate(perc = round(N/sum(N),2)), aes(x = readmitted, y = perc, fill = age, cumulative = TRUE)) + geom_col() +
 geom_text(aes(label = paste0(perc*100,"%")), 
              position = position_stack(vjust = 0.5))

changes <- table(diabetes_data$change, diabetes_data$readmitted)
colnames(changes) <- c("re-ad < 30 days", "re-ad > 30 days", "no re-ad")
changes_1 <- data.table(changes)
colnames(changes_1) <- c("ChangedMeds", "readmitted", "N")
ggplot(changes_1 %>% group_by(readmitted) , aes(x = readmitted, y = N, fill = ChangedMeds, cumulative = TRUE)) + geom_col()

ggplot(changes_1 %>% group_by(readmitted) %>% mutate(perc = round(N/sum(N),2)), aes(x = readmitted, y = perc, fill = ChangedMeds, cumulative = TRUE)) + geom_col() +
 geom_text(aes(label = paste0(perc*100,"%")), 
              position = position_stack(vjust = 0.5))
## Or another way
## For all data, Chi-Square of readamission versus gender

gender_test <- table(diabetes_data$gender, diabetes_data$readmitted)

gender_test <- gender_test[1:2,]

all_data_gender <- chisq.test(gender_test)

print(all_data_gender)

changed_meds_test <- chisq.test(changes)

print(changed_meds_test)

gender_changes <- table(diabetes_data$gender, diabetes_data$change)

print(changed_meds_test)

print(chisq.test(gender_changes))
## now, summarize the data

weight_all = summary(diabetes_data$weight)
print(weight_all)

print(chisq.test(weight_all))

yup <- table(diabetes_data$patient_nbr)

print(quantile(yup))
## For all data, Chi-Square for  race versus admission data


race_test <- table(diabetes_data$race, diabetes_data$readmitted)

race_test <- race_test[1:5,]

all_data_race <- chisq.test(race_test)

print(all_data_race)


## For all data, Chi-square for age versus readmission data


age_test <- table(diabetes_data$age, diabetes_data$readmitted)

age_test <- age_test[2:10,]

all_data_age <- chisq.test(age_test)

print(all_data_age)



## Evaluate only patients with multiple encounter IDs


Dupe_diabetes_data <- diabetes_data[diabetes_data$patient_nbr %in% names(which(table(diabetes_data$patient_nbr)>1)),]

## Duplicate patient ID, chi-square of  gender versus readmission


dupes_gender_table <- table(Dupe_diabetes_data$gender, Dupe_diabetes_data$readmitted)

dupes_gender_table <- dupes_gender_table[1:2,]

dupes_gender_test <- chisq.test(dupes_gender_table)

print(dupes_gender_test)

dupes_gender_test_1 <- data.table(dupes_gender_table)

colnames(dupes_gender_test_1) <- c("gender", "readmitted", "N")
ggplot(dupes_gender_test_1 %>% group_by(readmitted) , aes(x = readmitted, y = N, fill = gender, cumulative = TRUE)) + geom_col()

ggplot(dupes_gender_test_1 %>% group_by(readmitted) %>% mutate(perc = round(N/sum(N),2)), aes(x = readmitted, y = perc, fill = gender, cumulative = TRUE)) + geom_col() +
 geom_text(aes(label = paste0(perc*100,"%")), 
              position = position_stack(vjust = 0.5))

## Duplicate patient ID, chi-square of race versus readmission

dupes_race_table <- table(Dupe_diabetes_data$race, Dupe_diabetes_data$readmitted)

## Remove the unknown races

dupes_race_table <- dupes_race_table[2:5,]

dupes_race_test <- chisq.test(dupes_race_table)

print(dupes_race_test)

dupes_race_test_1 <- data.table(dupes_race_table)

colnames(dupes_race_test_1) <- c("race", "readmitted", "N")
ggplot(dupes_race_test_1 %>% group_by(readmitted) , aes(x = readmitted, y = N, fill = race, cumulative = TRUE)) + geom_col()

ggplot(dupes_race_test_1 %>% group_by(readmitted) %>% mutate(perc = round(N/sum(N),2)), aes(x = readmitted, y = perc, fill = race, cumulative = TRUE)) + geom_col() +
 geom_text(aes(label = paste0(perc*100,"%")), 
              position = position_stack(vjust = 0.5))

## Duplicate patient ID, chi-square of age versus readmission

dupe_age_table <- table(Dupe_diabetes_data$age, Dupe_diabetes_data$readmitted)

dupe_age_table <- dupe_age_table[2:10,]

dupe_age_test <- chisq.test(dupe_age_table)

print(dupe_age_test)

dupe_age_test_1 <- data.table(dupe_age_table)
colnames(dupe_age_test_1) <- c("age", "readmitted", "N")
ggplot(dupe_age_test_1 %>% group_by(readmitted) , aes(x = readmitted, y = N, fill = age, cumulative = TRUE)) + geom_col()

ggplot(dupe_age_test_1 %>% group_by(readmitted) %>% mutate(perc = round(N/sum(N),2)), aes(x = readmitted, y = perc, fill = age, cumulative = TRUE)) + geom_col() +
 geom_text(aes(label = paste0(perc*100,"%")), 
              position = position_stack(vjust = 0.5))


## Patients numbers only once (may have been readmitted)

No_duplicated_data <- diabetes_data[diabetes_data$patient_nbr %in% names(which(table(diabetes_data$patient_nbr)==1)),]

print(head(No_duplicated_data))

gender_nodupes_table <- table(No_duplicated_data$gender, No_duplicated_data$readmitted)

gender_nodupes_table <- gender_nodupes_table[1:2,]

gender_nodupes_test <- chisq.test(gender_nodupes_table)

print(gender_nodupes_test)

##  Now the race data

race_nodupes_table <- table(No_duplicated_data$race, No_duplicated_data$readmitted)

race_nodupes_table <- race_nodupes_table[2:5,]

race_nodupes_test <- chisq.test(race_nodupes_table)

print(race_nodupes_test)

##  Now for the age data

age_nodupes_table <- table(No_duplicated_data$age, No_duplicated_data$readmitted)

age_nodupes_table <- age_nodupes_table[2:10,]

age_nodupes_test <- chisq.test(age_nodupes_table)

print(age_nodupes_test)

##  Some plots



## remove ? for race






```
